doctrine_mongodb:
    auto_generate_proxy_classes: '%kernel.debug%'
    auto_generate_hydrator_classes: '%kernel.debug%'
    connections:
        default:
            server: 'mongodb://%mongodb_user%:%mongodb_password%@%mongodb_server%:%mongodb_port%'
            options: {}
    default_database: '%mongodb_database%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/App/Document'
                    prefix: App\Document\
                    alias: App
                AppMainBundle:
                    is_bundle: true
                    type: annotation
                    dir: 'Document'
                    prefix: App\MainBundle\Document\
                    alias: AppMainBundle

#doctrine_cache:
#    aliases:
#        mongodb_cache: mongodb_cache
#    providers:
#        mongodb_cache:
#            mongodb:
#                connection_id: mongo.connection
#                collection_id: mongo.cache_collection
#                server: 'mongodb://%mongodb_user%:%mongodb_password%@%mongodb_server%:%mongodb_port%'
#                database_name: '%mongodb_database%'
#                collection_name: 'cache'
#            aliases:
#                - mongodb_cache