imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: settings.yml }

framework:
    #esi: ~
    translator:
        fallbacks: ['en']
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer:
        enable_annotations: true
        enabled: true
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   '%kernel.root_dir%/../var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets:
        version: '%app_version%'
        packages:
            vendor:
                version: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    form_themes: ['bootstrap_4_layout.html.twig']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        app_name: '%app_name%'
        app_logo_image_url: '%logo_image_url%'

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    port: '%mailer_port%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    encryption: '%mailer_encryption%'
    auth_mode: '%mailer_auth_mode%'
    spool: { type: memory }

# Doctrine Configuration
doctrine:
#    dbal:
#        driver: pdo_mysql
#        host: '%database_host%'
#        port: '%database_port%'
#        dbname: '%database_name%'
#        user: '%database_user%'
#        password: '%database_password%'
#        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

#    orm:
#        auto_generate_proxy_classes: '%kernel.debug%'
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true

doctrine_mongodb:
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: "mongodb://%mongodb_user%:%mongodb_password%@%mongodb_server%"
            options: {}
    default_database: "%mongodb_database%"
    document_managers:
        default:
            auto_mapping: true

doctrine_cache:
    aliases:
        mongodb_cache: mongodb_cache
    providers:
        mongodb_cache:
            mongodb:
                connection_id: mongo.connection
                collection_id: mongo.cache_collection
                server: 'mongodb://%mongodb_user%:%mongodb_password%@%mongodb_server%'
                database_name: "%mongodb_database%"
                collection_name: "cache"
            aliases:
                - mongodb_cache

liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: '%kernel.root_dir%/../web'
    resolvers:
        default:
            web_path:
                web_root: '%kernel.root_dir%/../web'
                cache_prefix: 'uploads/thumbs/cache'
    filter_sets:
        cache: ~

        thumb_small:
            quality: 85
            filters:
                relative_resize:
                    widen: 200
                thumbnail: { size: [200, 200], mode: inset }
                background: { size: [200, 200], position: center, color: '#ffffff' }

        thumb_medium:
            quality: 85
            filters:
                relative_resize:
                    widen: 400
                thumbnail: { size: [400, 400], mode: inset }
                background: { size: [400, 400], position: center, color: '#ffffff' }

        thumb_big:
            quality: 90
            filters:
                relative_resize:
                    widen: 800
                thumbnail: { size: [800, 800], mode: inset }
                background: { size: [800, 800], position: center, color: '#ffffff' }
