#omnipay:
#    resource: "@OmnipayBundle/Resources/config/routing.yml"
#    prefix: /

homepage:
    path: /
    defaults:
        _controller: AppBundle\Controller\DefaultController::homepageAction

logout:
    path: /logout

admin:
    resource: '@AppBundle/Controller/Admin/'
    type: annotation

_liip_imagine:
    resource: '@LiipImagineBundle/Resources/config/routing.xml'

app_annotations:
    resource: '@AppBundle/Controller/'
    type: annotation
