homepage:
    path: '/'
    defaults: { _controller: AppBundle\Controller\DefaultController::homepageAction }

admin:
    resource: '@AppBundle/Controller/Admin/'
    type: annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
    path: /logout
