# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    kernel_event_listener:
        class: AppBundle\EventListener\KernelEventListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }
        arguments: [ '@service_container' ]

    mongodb_paramconverter:
        class: Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter
        arguments: ["@doctrine_mongodb"]
        tags:
            - { name: request.param_converter }

    mongo.connection:
        class: Doctrine\MongoDB\Connection
        factory: ["@doctrine.odm.mongodb.document_manager", getConnection]
        calls:
            - [initialize, []]

    mongo:
        class: Mongo
        factory: ["@mongo.connection", getMongo]
