# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    kernel_event_listener:
        class: AppBundle\EventListener\KernelEventListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }
        arguments: [ '@service_container' ]