omnipay:
    resource: "@OmnipayBundle/Resources/config/routing.yml"
    prefix: /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

homepage:
    path: /
    defaults:
        _controller: App\Controller\DefaultController::homepageAction

logout:
    path: /logout

plugins:
    resource: ../../vendor/shk4-plugins/
    type: annotation

controllers:
    resource: ../../src/App/Controller/
    type: annotation
