menu:
    - { title: 'ORDERS', route: '/orders', icon: 'icon-bag' }
    - { title: 'CATALOG', route: '/catalog', icon: 'icon-layers' }
#    - { title: 'STATISTICS', route: '/statistics', icon: 'icon-bar-graph-2' }
    - { title: 'USERS', route: '/users', icon: 'icon-head' }
    - { title: 'TEMPLATES', route: '/templates_edit', icon: 'icon-columns' }
#    - { title: 'IMPORT_EXPORT', route: '/module/import-export/import', icon: 'icon-inbox' }
    - { title: 'SETTINGS', route: '/settings', icon: 'icon-cog' }