AppBundle\Document\Category:
    type: document
    collection: category
    repositoryClass: AppBundle\Repository\CategoryRepository
    fields:
        id:
            type: id
            id: true
            strategy: INCREMENT
        parent_id:
            type: int
        title:
            type: string
        name:
            type: string
        description:
            type: string
        content_type:
            type: string
        is_folder:
            type: boolean
        is_active:
            type: boolean
    lifecycleCallbacks: {}